# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('app_link', models.URLField()),
                ('api_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
