"""
Django settings for ombudsman project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['OMBUDSMAN_DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["ombudsman.user.camp", "ombudsman-uc.herokuapp.com"]

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'ombudsman',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'captcha'
]

# Recaptcha

NOCAPTCHA = True
RECAPTCHA_PUBLIC_KEY = os.environ['OMBUDSMAN_RECAPTCHA_PUBLIC_KEY']
RECAPTCHA_PRIVATE_KEY = os.environ['OMBUDSMAN_RECAPTCHA_PRIVATE_KEY']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rollbar.contrib.django.middleware.RollbarNotifierMiddleware'
]

ROOT_URLCONF = 'ombudsman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ombudsman.wsgi.application'

# Rollbar

ROLLBAR = {
    'access_token': os.environ['OMBUDSMAN_ROLLBAR_ACCESS_TOKEN'],
    'environment': 'development',
    'branch': 'master',
    'root': '/',
}


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

import dj_database_url
DATABASES = {'default': dj_database_url.config()}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/


STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Sendgrid

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = os.environ['OMBUDSMAN_SENDGRID_USERNAME']
EMAIL_HOST_PASSWORD = os.environ['OMBUDSMAN_SENDGRID_PASSWORD']
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# App globals

AZURE_AD_ENDPOINT = "https://login.microsoftonline.com/{}/oauth2/token"
ROOT_API_ENDPOINT = "https://manage.devcenter.microsoft.com/v1.0/my/analytics/"

API_ENDPOINTS = {
    'reviews': ROOT_API_ENDPOINT + "reviews/",
    'acquisitions': ROOT_API_ENDPOINT + "appacquisitions/",
    'add_on_acquisitions': ROOT_API_ENDPOINT + "inappacquisitions/",
    'installs': ROOT_API_ENDPOINT + "installs/",
    'ratings': ROOT_API_ENDPOINT + "ratings/",
    'ads_performance': ROOT_API_ENDPOINT + "adsperformance/",
    'ad_campaign_performance': ROOT_API_ENDPOINT + "promotion/",
    'errors': ROOT_API_ENDPOINT + "failurehits/"
}
